require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task default: ["spec", "rubocop:auto_correct"]

desc "Build Site"
task :build do
require "middleman-gh-pages"
  rake build

desc "Publish Site"
task :publish do
require "middleman-gh-pages"
  rev = `git rev-parse --short HEAD`.chomp
  rake publish PROJECT_ROOT= `#{rev}/standards-catalogue`